---
apiVersion: v1
kind: Service
metadata:
  name: nfs-service
spec:
  selector:
    service: nfs
  ports:
    - name: nfs
      port: 2049
    - name: mountd
      port: 20048
    - name: rpcbind
      port: 111
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-server
spec:
  selector:
    matchLabels:
      role: nfs-server
  template:
    metadata:
      name: nfs-server
      labels:
        role: nfs-server
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: kubernetes.io/hostname
                  operator: In
                  values:
                    - pve
      containers:
        - name: alpine
          image: alpine
          ports:
            - containerPort: 2049
            - containerPort: 20048
            - containerPort: 111

